name: Ship js trigger
on:
  pull_request:
    types:
      - closed
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }} == true && startsWith(${{ github.head_ref }}, 'releases/v');
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: 'npm'
      - run: |
          npm ci
      - run: |
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"
          npx shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
